image: $IMAGE_REGISTRY/workplatform/mvn

variables:
  DOCKER_DRIVER: overlay
  NAMESPACE: dlink-test
  SERVICE_NAME: sensecloud-analysis
  IMAGE_REGISTRY: registry.sensetime.com
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_STRATEGY: clone
  GIT_CHECKOUT: "true"
  APP_IMAGE: $IMAGE_REGISTRY/plat-bigdata/$SERVICE_NAME
  PREFIX_TAG: test_v1


stages:
#  - code_scan
  - build
  - package
#  - deploy

#job_code_scan2:
#  image: registry.sensetime.com/security/codescan:latest
#  stage: code_scan
#  only:
#    - test
#  script:
#    - sonar_full_scan.sh
#  tags:
#    - k8s

maven-build:
  image: $IMAGE_REGISTRY/workplatform/mvn
  stage: build
  only:
    - test
  tags:
    - maven
  script:
    - mvn clean package -Dmaven.test.skip=true
  artifacts:
    paths:
      - ./web/target/*.jar

docker-build:
  image: $IMAGE_REGISTRY/docker.io/docker:19.03.8
  stage: package
  only:
    - test
  script:
    - export TAG=$PREFIX_TAG-${CI_COMMIT_SHA:0:8}
    - docker build -t $APP_IMAGE:$TAG ./
    - docker login $IMAGE_REGISTRY -u $RES_USER -p $RES_PASSWD
    - docker push $APP_IMAGE:$TAG

#k8s-deploy:
#  image: $IMAGE_REGISTRY/plat-bigdata/dlink-test-diamond-kube:latest
#  stage: deploy
#  only:
#    - test
#  dependencies: []
#  script:
#    - export TAG=$PREFIX_TAG-${CI_COMMIT_SHA:0:8}
#    - kubectl set image deployment/$SERVICE_NAME $SERVICE_NAME=$APP_IMAGE:$TAG -n $NAMESPACE