spring:
  profiles:
    test
  datasource:
    # SQL 性能分析 p6spy 代理
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://sh.paas.sensetime.com:34004/sensecloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: 9mmyxokq
    password: bxzqx4f5

mybatis-plus:
  typeAliasesPackage: sensecloud.sso.entity
  configuration:
    # 输出构造 SQL 过程
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: sensecloud-analysis-swagger-openapi
  # https://${server.address}:${server.port}/swagger-ui/index.html
  try-host: http://${server.address}:${server.port}

service:
  sso:
    domain: bigdata
    id_token_header: X-Id-Token
    access_token_header: access_token
    no_auth_redirect_url: https://sensecloud-dev.sensetimetech.cn/login
    logout_uri: /logout
    logout_redirect_url: https://sensecloud-dev.sensetimetech.cn/logout?redirect_uri=https://bigdata-dev.sensetimetech.cn
    rest-api:
      url: https://sso-sc-dev.sensetime.com
      endpoints:
        userinfo: /userinfo
  connector:
    upload:
      path: /tmp/sensecloud
    rule:
      path: connector/rule
    clickhouse:
      url: jdbc:clickhouse://10.53.7.100:33334
      des.key: dlink@2020
  submitter:
    airflow:
      conf:
        templatePath: airflow/dag
      git:
        localRepo: /git
        project: sensecloud-analysis
        remoteUrl: https://gitlab.bj.sensetime.com/plat-bigdata/airflow-dags-prod.git
        username: sre.bigdata
        password: Dlink@6666
        remoteBranch: test
        remote: origin
    env:
      k8s.context: aliyun-hd1-diamond
      k8s.namespace: dlink-prod
      k8s.oauth_token: kubeconfig-u-2n2gk7efdi:tjg4ckq6nvps7xg6cdlg64fjvwqtdmrtnhkpjzhtshxrdlj4n7cf6b
      k8s.api_server: k8s://https://mordor.sensetime.com/k8s/clusters/c-kzszr

remote:
  rest:
    mysql_cdc:
      url: http://10.10.18.109:49018/mysql-cdc/api/v1
    airflow:
      url: http://10.10.18.109:45688
      username: sre.bigdata
      password: Dlink@6666
      provider: ldap

