spring:
  datasource:
    # SQL 性能分析 p6spy 代理
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://bj.paas.sensetime.com:34832/sensecloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: 9mmyxokq
    password: bxzqx4f5

mybatis-plus:
  typeAliasesPackage: sensecloud.sso.entity
  configuration:
    # 输出构造 SQL 过程
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: sensecloud-analysis-swagger-openapi
  try-host: http://${server.address}:${server.port}

sso:
  rest-api:
    url: https://sso-sc-dev.sensetime.com
    endpoints:
      userinfo: /userinfo


connector:
  rule:
    path: connector/rule

submitter:
  airflow:
    conf:
      templatePath: airflow/dag
    git:
      localRepo: /git
      project: sensecloud-analysis
      remoteUrl: https://gitlab.bj.sensetime.com/plat-bigdata/airflow-dags-prod.git
      username: sre.bigdata
      password: Dlink@6666
      remoteBranch: test
      remote: origin
    k8s:
      namespace: dlink-test

