spring:
  application:
    name: sensecloud-analysis
  profiles:
    active: test

#server:
#  port: 8443
#  ssl:
#    protocol: TLS
#    key-store: classpath:.keystore
#    key-store-password: 123456
#    key-store-type: JKS